name: Dart

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dart:stable  # or dart:3.2.3 for specific version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Dart installation
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test

      - name: Generate coverage
        run: |
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage
        continue-on-error: true